### ISSUE TITLE
atom-xikij breaks multiline comments

### ISSUE THREAD

**Issue by josa42** [klorenz/atom-xikij#2]
I noticed that when I have the atom-xikij package installed multiline comments are not correctly recognised anymore (JavaScript).

This is what it looks like with atom-xikij installed:
![screen shot 2014-11-04 at 10 56 27](https://cloud.githubusercontent.com/assets/423234/4897820/c5ba54f0-6409-11e4-9598-6d930e5753f0.png)

This is what it looks like without
![screen shot 2014-11-04 at 10 54 04](https://cloud.githubusercontent.com/assets/423234/4897818/c21607ae-6409-11e4-863b-e27f4cebadac.png)

I am using:
- Atom 1.41.0
- Atom Xikij 0.7.7

**Comment by klorenz** [comment]
Omg, die not Look at this package for years!

Josa Gesell <notifications@github.com> schrieb am Fr., 5. Feb. 2021, 22:45:
